version: '3.9'

services:
  web:
    build: .
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/trello
    ports:
      - 8000:8000
    env_file:
      - .envs/.env
    depends_on:
      - trello_db


  trello_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=trello_admin
      - POSTGRES_PASSWORD=qwerty12345
      - POSTGRES_DB=trello_db

volumes:
  postgres_data:
