# Generated by Django 4.1.3 on 2022-11-24 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_board_members_alter_board_background_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='boards.board'),
        ),
    ]
