# Generated by Django 4.1.3 on 2022-12-09 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_remove_board_file_remove_card_mark_mark_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='boards.board'),
        ),
    ]
